# Generated by Django 4.1.1 on 2023-07-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_account_example_prismamigrations_session_testtest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDjangoModel',
        ),
    ]
