# Generated by Django 6.0 on 2025-12-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_delete_account_delete_example_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_id',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.CharField(default='Domicile', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.CharField(db_index=True, default='', max_length=255),
        )
    ]
