# Generated by Django 4.1.1 on 2023-07-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.CharField(default='Domicile', max_length=255),
        ),
    ]
