# Generated by Django 6.0 on 2026-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_transportoption_customuser_is_accounting_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ice',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Supplier catalogue reference, e.g. 1J0122291. Used on comptabilité invoices.', max_length=100, verbose_name='Supplier Reference'),
        ),
        migrations.AddField(
            model_name='provider',
            name='ice',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
