# Generated by Django 4.1.1 on 2023-07-01 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0019_optioncategories_alter_echeance_dateecheance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.CharField(default='CTM', max_length=255),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='dateEcheance',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 19, 36, 57, 965183, tzinfo=datetime.timezone.utc)),
        ),
    ]
