# Generated by Django 4.1.1 on 2023-07-05 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0020_order_transport_alter_echeance_dateecheance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('provider', models.TextField()),
                ('provideraccountid', models.TextField(db_column='providerAccountId')),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.IntegerField(blank=True, null=True)),
                ('token_type', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True, null=True)),
                ('session_state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'Example',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrismaMigrations',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('migration_name', models.CharField(max_length=255)),
                ('logs', models.TextField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('applied_steps_count', models.IntegerField()),
            ],
            options={
                'db_table': '_prisma_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('sessiontoken', models.TextField(db_column='sessionToken', unique=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'Session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testtest',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TestTest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('isadmin', models.BooleanField(db_column='isAdmin')),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinformation',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('cin', models.TextField()),
                ('naissance', models.DateTimeField()),
                ('address', models.TextField()),
                ('tel', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'UserInformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verificationtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('token', models.TextField(unique=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'VerificationToken',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='echeance',
            name='dateEcheance',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 20, 14, 40, 903436, tzinfo=datetime.timezone.utc)),
        ),
    ]
