# Generated by Django 4.1.1 on 2023-07-05 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0023_alter_echeance_dateecheance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance',
            name='dateEcheance',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 20, 21, 11, 924515, tzinfo=datetime.timezone.utc)),
        ),
    ]
