# Generated by Django 4.1.1 on 2023-07-05 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0024_alter_echeance_dateecheance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testtest',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TestTest',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='echeance',
            name='dateEcheance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
