# Generated by Django 4.1.1 on 2023-07-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0025_testtest_alter_echeance_dateecheance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testtest',
        ),
    ]
