# Generated by Django 4.1.1 on 2023-07-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0026_delete_testtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testtest',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TestTest',
                'managed': False,
            },
        ),
    ]
