# Generated by Django 4.1.1 on 2023-07-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0027_testtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testtest',
        ),
    ]
