# Generated by Django 6.0 on 2026-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinginvoice',
            name='custom_reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional custom reference printed on the invoice instead of the system number.', max_length=100, verbose_name='Custom Reference / Printed Number'),
        ),
    ]
