# Generated by Django 6.0 on 2026-10-01 18:03

import django.utils.timezone
from django.db import migrations, models


def backfill_invoice_date(apps, schema_editor):
    AccountingInvoice = apps.get_model('accounting', 'AccountingInvoice')
    # Existing rows got timezone.now at ADD COLUMN time — restore true date from created_at
    for inv in AccountingInvoice.objects.all().only('id', 'invoice_date', 'created_at'):
        if inv.invoice_date and inv.created_at and abs((inv.invoice_date - inv.created_at).total_seconds()) > 60:
            # invoice_date is migration-time now(), created_at is real → fix
            AccountingInvoice.objects.filter(pk=inv.pk).update(invoice_date=inv.created_at)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_custom_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinginvoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='Editable accounting date printed on the invoice. Defaults to creation time.', null=True, verbose_name='Invoice Date'),
        ),
        migrations.RunPython(backfill_invoice_date, noop),
    ]
