# Generated by Django 6.0 on 2026-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Supplier catalogue reference printed on the invoice.', max_length=100, verbose_name='Product Reference'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price_ttc',
            field=models.FloatField(default=0),
        ),
    ]
