# Generated by Django 6.0 on 2026-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_invoiceitem_reference_invoiceitem_unit_price_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinginvoice',
            name='invoice_type',
            field=models.CharField(choices=[('ACHAT', 'Achat (Purchase)'), ('VENTE', 'Vente (Sale)'), ('AVOIR', 'Avoir (Credit Note)')], max_length=5),
        ),
    ]
