# Generated by Django 6.0 on 2026-10-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_accountinginvoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.FloatField(default=0, help_text='Line discount percent, e.g. 35 = -35%. Applied on the TTC line total.', verbose_name='Remise (%)'),
        ),
    ]
